export const POSTS_PER_PAGE = 3
export const posts = [
  {
    title: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    category: "style",
    image: "/display-icons/categories/style.png",
    href: "/blog?category=style",
    customStyles: { backgroundColor: "#ff7857" },
    author: "John Doe",
    date: "11.02.2023",
  },
  {
    title: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    category: "fashion",
    image: "/display-icons/categories/fashion.png",
    href: "/blog?category=fashion",
    customStyles: { backgroundColor: "#ffb14f" },
    author: "John Doe",
    date: "11.02.2023",
  },
  {
    title: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    category: "food",
    image: "/display-icons/categories/food.png",
    href: "/blog?category=food",
    customStyles: { backgroundColor: "#7fb881" },
    author: "John Doe",
    date: "11.02.2023",
  },
  {
    title: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    category: "travel",
    image: "/display-icons/categories/travel.png",
    href: "/blog?category=travel",
    customStyles: { backgroundColor: "#775aec" },
    author: "John Doe",
    date: "11.02.2023",
  },
  {
    title: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    category: "culture",
    image: "/display-icons/categories/culture.png",
    href: "/blog?category=culture",
    customStyles: { backgroundColor: "#ff7887" },
    author: "John Doe",
    date: "11.02.2023",
  },
  {
    title: "Lorem ipsum dolor, sit amet consectetur adipisicing elit.",
    category: "coding",
    image: "/display-icons/categories/coding.png",
    href: "/blog?category=coding",
    customStyles: { backgroundColor: "#4fff31" },
    author: "John Doe",
    date: "11.02.2023",
  },
];
