export const users = [{
'Id':	'The unique id to identify the user.',
'First Name': '	The first name of the user.',
'Middle Name': 'Name	The middle name of the user.',
'Last Name': 'Name	The last name of the user.',
'Mobile':	'The mobile number of the user. It can be used for login and registration purposes.',
'Email':	'The email of the user. It can be used for login and registration purposes.',
'Password': 'Hash	The password hash generated by the appropriate algorithm. We must avoid storing plain passwords.',
'Registered': 'At	This column can be used to calculate the life of the user with the blog.',
'Last': 'Login	It can be used to identify the last login of the user.',
'Intro':	'The brief introduction of the Author to be displayed on each post.',
'Profile':	'',
}]